#!/usr/bin/env bash
set -euo pipefail

# Train PF-MSBNet-A2:
# MIMO-structured pilot TokenFormer encoder + relative pilot attention +
# basis-pilot cross attention + closed-form pilot fitting.

TOKEN_ENCODER="${TOKEN_ENCODER:-mimo_tokenformer}" \
USE_ATTENTION="${USE_ATTENTION:-1}" \
ATTENTION_HEADS="${ATTENTION_HEADS:-4}" \
ATTENTION_LAYERS="${ATTENTION_LAYERS:-1}" \
LINK_ATTENTION_HEADS="${LINK_ATTENTION_HEADS:-4}" \
LINK_ATTENTION_LAYERS="${LINK_ATTENTION_LAYERS:-1}" \
LINK_ATTENTION_DROPOUT="${LINK_ATTENTION_DROPOUT:-0}" \
ATTENTION_DROPOUT="${ATTENTION_DROPOUT:-0}" \
GATE_DROPOUT="${GATE_DROPOUT:-0}" \
BASIS_DROPOUT="${BASIS_DROPOUT:-0}" \
PILOT_NOISE_STD="${PILOT_NOISE_STD:-0}" \
LAMBDA_GATE="${LAMBDA_GATE:-1e-5}" \
LAMBDA_GATE_ENTROPY="${LAMBDA_GATE_ENTROPY:-0}" \
LAMBDA_ATTENTION_ENTROPY="${LAMBDA_ATTENTION_ENTROPY:-0}" \
EARLY_STOPPING_PATIENCE="${EARLY_STOPPING_PATIENCE:-6}" \
OUTDIR="${OUTDIR:-}" \
bash scripts/server_train_pf_msbnet.sh
